config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root    'static_pages#home'
  get     'help',         to: 'static_pages#help'
  get     'about',        to: 'static_pages#about'
  get     'contact',      to: 'static_pages#contact'
  get     'signup',       to: 'users#new'
  post    'signup',       to: 'users#create'
  get     'login',        to: 'sessions#new'
  delete  'logout',       to: 'sessions#destroy'
  get     'search',       to: 'photos#index'
  get     'favorites',    to: 'photos#favorite'
  delete  'delete',       to: 'photos#destroy'
  get     'galleries',    to: 'galleries#index'
  get     'new_albums',       to: 'albums#new'
  post    'new_albums',       to: 'albums#create'

  resources :users
  resources :photos
  resources :sessions
  resources :albums
  resources :album_photos
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
end

app/models/album_photo.rb
class AlbumPhoto < ApplicationRecord
  belongs_to :photo
  belongs_to :album
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :albums , dependent: :destroy

  before_save { email.downcase! }

  validates :password, length: { minimum: 3 },
                       if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true,
                       if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true,
                                    if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/album_photos_controller.rb
class AlbumPhotosController < ApplicationController
end

app/controllers/albums_controller.rb
# frozen_string_literal: true

class AlbumsController < ApplicationController
  def index
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:success] = 'Picture was liked'
    else
      render 'new'
    end
  end

  def favorite
    @photos = Photo.all
  end

  def destroy
    Album.find(params[:id]).destroy
    flash[:info] = 'Picture was deleted'
  end

  private

  def album_params
    params.require(:album).permit(:title)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include PhotosHelper
end

# ssh -R 80:localhost:3000 ssh.localhost.run
# http:// thanh-92f052c7 . localhost .run/
# https://github.com/C190353/task/tree/like-photo
#
# ID: example@example.com
# Pass: example
#
# Tui đã làm được tới chổ search và trả về kết quả.  (views/photos/index.html.erb)
#
# Bây giờ tui muốn lưu thông tin của tấm ảnh vào DB
# bằng cách click vào 1 button, nhưng code mình đang viết
# như vậy thì không xài được. (views/photos/create.html.erb)
#
# Mọi người có thể chỉ tui keyword nào để tìm xem làm như thế nào được không?

app/controllers/photos_controller.rb
# frozen_string_literal: true

class PhotosController < ApplicationController
  def index
    @photo = Photo.new
    search_image
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = 'Picture was liked'
    end
end

  def favorite
    @photos = Photo.all
  end

  def destroy
    Photo.find(params[:id]).destroy
    flash[:info] = 'Picture was deleted'
  end

  private

  def photo_params
    params.require(:photo).permit(:farm, :server, :flickr_id, :secret)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = login(params[:email], params[:password])
    if user
      redirect_back_or_to search_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    logout
    flash[:info] = 'Logged out'
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = "Your account has been created!"
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
    )
  end
end

app/helpers/album_photos_helper.rb
module AlbumPhotosHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Ruby on Rails Tutorial Sample App'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/photos_helper.rb
# frozen_string_literal: true

module PhotosHelper
  def search_image
    if params[:commit] == 'submit' && !params[:search_text].empty?
      conn = Faraday.new(url: 'https://www.flickr.com') do |faraday|
        faraday.request  :url_encoded
        faraday.response :logger
        faraday.adapter  Faraday.default_adapter
      end

      response = conn.get do |req|
        req.url '/services/rest/'
        req.params['api_key'] = '477a1f3be8d4f207638152397e09f0f2'
        req.params['format'] = 'json'
        req.params['method'] = 'flickr.photos.search'
        req.params['text'] = params[:search_text]
        req.params['nojsoncallback'] = '1'
        req.params['per_page'] = '10'
      end
      jsonDocument = JSON.parse(response.body)
      @photo_list = jsonDocument['photos']['photo']
      # @photo_list = photos['photo']
    end
  end

  def photo_in_gallery?(id)
    !Photo.where(flickr_id: id).blank?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # def gravatar_for(user, size: 80)
  #   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  #   size = options[:size]
  #   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  #   image_tag(gravatar_url, alt: user.name, class: "gravatar")
  # end
end

# <%= gravatar_for @user %>
# users/show.html.erb

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

app/views/albums/index.html.erb
<h1>Albums#index</h1>
<p>Find me in app/views/albums/index.html.erb</p>

app/views/albums/new.html.erb
<% provide(:title, 'Create Album') %>
  <h1>Create album</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with model: @album, local: true do |f| %>

      <%= f.label :title %><br/>
      <%= f.text_field :title , class: 'form-control' %>


      <%= f.submit "Create my album", class: "btn btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/albums/show.html.erb
<% provide(:title, @album.title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @album.title %>
      </h1>
    </section>
  </aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>

        <% if logged_in? %>
          <li>
            <%= link_to "Search", search_path %>
          </li>
          <li>
            <%= link_to "Favor", favorites_path %>
          </li>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", '#' %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li><%= link_to "Gallery", galleries_path %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application',
                               'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>
      <%= yield %>
  <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/photos/favorite.html.erb
<% provide(:title, 'Favorites') %>
  <h1>Favorites</h1>

  <% @photos.each do |photo| %>
    <img src='http://farm<%= photo.farm %>.staticflickr.com/<%= photo.server
                            %>/<%= photo.flickr_id %>_<%= photo.secret %>.jpg'>
    <%= button_to "Delete", photo_path(:id => photo.id), :method => :delete %>

  <% end %>

app/views/photos/index.html.erb
<% provide(:title, 'Search') %>
  <h1>Search Image</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_tag(search_path, method: 'get') do %>
      <%= label_tag :search_text, 'Search text:' %>
      <%= text_field_tag :search_text, '', placeholder: 'Enter text search', class: 'form-control' %>
      <%= submit_tag :submit, class: "btn btn-primary"%>
    <% end %>

  </div>
</div>

<div class="row">

  <% if @photo_list %>
    <p><%= label_tag :list_photo, 'Result' %></p>
    <div class="col-xs-6 col-sm-3 col-md-15">

      <% @photo_list.each_with_index do |photo| %>

        <img src='http://farm<%= photo["farm"] %>.staticflickr.com/<%= photo["server"]
                %>/<%= photo["id"] %>_<%= photo["secret"] %>.jpg'>
        <%= button_to 'Like', photos_path(photo: {farm: photo["farm"], server: photo["server"],
                                          flickr_id: photo["id"], secret: photo["secret"]}) %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture %>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>

  </span>
<% end %>
<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :email %><br />
        <%= f.text_field :email , class: 'form-control' %>

        <%= f.label :password %><br />
        <%= f.password_field :password , class: 'form-control' %>

        <%= f.label :password_confirmation , "Confirmation" %><br />
        <%= f.password_field :password_confirmation , class: 'form-control'%>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.email %>
      </h1>
    </section>
  </aside>
</div>